# Generated by Django 5.0.6 on 2024-05-23 15:06

import django.db.models.deletion # type: ignore
from django.db import migrations, models # type: ignore


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("tendangnhap", models.CharField(max_length=100)),
                ("matkhau", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="SanPham",
            fields=[
                ("MaSanPham", models.AutoField(primary_key=True, serialize=False)),
                ("TenSanPham", models.CharField(max_length=255)),
                ("MoTa", models.TextField()),
                ("Gia", models.FloatField()),
                (
                    "HinhAnhDaiDien",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("NhanHieu", models.CharField(blank=True, max_length=100, null=True)),
                ("ChatLieu", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DanhMuc",
            fields=[
                ("MaDanhMuc", models.AutoField(primary_key=True, serialize=False)),
                ("TenDanhMuc", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="DonHang",
            fields=[
                ("MaDonHang", models.AutoField(primary_key=True, serialize=False)),
                ("NgayDatHang", models.DateField()),
                ("TongTien", models.DecimalField(decimal_places=2, max_digits=10)),
                ("DiaChiGiaoHang", models.CharField(max_length=255)),
                ("TrangThai", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="KhachHang",
            fields=[
                ("MaKhachHang", models.AutoField(primary_key=True, serialize=False)),
                ("Ten", models.CharField(max_length=100)),
                ("DiaChi", models.CharField(max_length=255)),
                ("SoDienThoai", models.CharField(max_length=20)),
                ("Email", models.EmailField(max_length=255, unique=True)),
                ("TenDangNhap", models.CharField(max_length=100)),
                ("MatKhau", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="KhuyenMai",
            fields=[
                ("MaKhuyenMai", models.AutoField(primary_key=True, serialize=False)),
                ("TenKhuyenMai", models.CharField(max_length=100)),
                ("NgayBatDau", models.DateField()),
                ("NgayKetThuc", models.DateField()),
                ("MoTa", models.TextField()),
                ("GiamGia", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ChiTietSanPham",
            fields=[
                (
                    "MaSanPham",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="handbagsMaketplace.sanpham",
                    ),
                ),
                ("MauSac", models.CharField(max_length=50)),
                (
                    "HinhAnhChiTiet",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("SoLuong", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="sanpham",
            name="MaDanhMuc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="handbagsMaketplace.danhmuc",
            ),
        ),
        migrations.CreateModel(
            name="ChiTietDonHang",
            fields=[
                (
                    "MaChiTietDonHang",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("SoLuong", models.IntegerField()),
                ("DonGia", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "MaSanPham",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="handbagsMaketplace.sanpham",
                    ),
                ),
                (
                    "MaDonHang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="handbagsMaketplace.donhang",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="donhang",
            name="MaKhachHang",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="handbagsMaketplace.khachhang",
            ),
        ),
        migrations.AddField(
            model_name="donhang",
            name="MaKhuyenMai",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="handbagsMaketplace.khuyenmai",
            ),
        ),
    ]
