# Generated by Django 5.0.6 on 2024-05-22 09:52

import django.db.models.deletion # type: ignore
from django.db import migrations, models # type: ignore


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tendangnhap", models.CharField(max_length=100)),
                ("matkhau", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ChiTietSanPham",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("MauSac", models.CharField(max_length=50)),
                (
                    "HinhAnhChiTiet",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("SoLuong", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="DanhMuc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("TenDanhMuc", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="KhachHang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Ten", models.CharField(max_length=100)),
                ("DiaChi", models.CharField(max_length=255)),
                ("SoDienThoai", models.CharField(max_length=20)),
                ("Email", models.EmailField(max_length=255, unique=True)),
                ("TenDangNhap", models.CharField(max_length=100)),
                ("MatKhau", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="KhuyenMai",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("TenKhuyenMai", models.CharField(max_length=100)),
                ("NgayBatDau", models.DateField()),
                ("NgayKetThuc", models.DateField()),
                ("MoTa", models.TextField()),
                ("GiamGia", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="DonHang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("NgayDatHang", models.DateField()),
                ("TongTien", models.DecimalField(decimal_places=2, max_digits=10)),
                ("DiaChiGiaoHang", models.CharField(max_length=255)),
                ("TrangThai", models.BooleanField(default=False)),
                (
                    "MaKhachHang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="handbagsMaketplace.khachhang",
                    ),
                ),
                (
                    "MaKhuyenMai",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="handbagsMaketplace.khuyenmai",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SanPham",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("TenSanPham", models.CharField(max_length=255)),
                ("MoTa", models.TextField()),
                ("Gia", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "HinhAnhDaiDien",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("NhanHieu", models.CharField(blank=True, max_length=100, null=True)),
                ("ChatLieu", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "MaDanhMuc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="handbagsMaketplace.danhmuc",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChiTietDonHang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("SoLuong", models.IntegerField()),
                ("DonGia", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "MaDonHang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="handbagsMaketplace.donhang",
                    ),
                ),
                (
                    "MaSanPham",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="handbagsMaketplace.sanpham",
                    ),
                ),
            ],
        ),
    ]
