# Generated by Django 5.0.6 on 2024-05-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("handbagsMaketplace", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sanpham",
            name="HinhAnhDaiDien",
            field=models.ImageField(upload_to="static/img"),
        ),
    ]
